name: Deploy to Development

on:
  push:
    branches:
      - main # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Or your desired version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements.txt file
          pip install google-api-python-client google-auth google-auth-oauthlib

      - name: Set up Environment Variables
        run: |
          echo "GMAIL_CLIENT_SECRET=$"{{ secrets.GMAIL_CLIENT_SECRET }}" > .env
          # Add other environment variables as needed

      - name: Run the script
        run: |
          python gmail_assistant.py # Or the name of your main script